sudo: required

language: scala

scala:
  - 2.12.0
  - 2.11.8

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker pull jplock/zookeeper:3.4.10

script: sbt constructr-coordination-zookeeper/test constructr-akka-testing/test
